---
title: "Graphics for M06 questions"
author: "Daniel Kaplan"
---

```{r include=FALSE}
library(Zcalc)
save_graph <- function(P, filename, font_size=16) {
  ggsave(filename, 
         P + theme_bw(base_size = font_size), 
         device="png", units="cm", width=10, scale=1, height=6, dpi="screen")
}

```

```{r}
P0 <- ggplot(data=Engines, aes(x=bore, y=stroke)) +
  geom_blank() +
  labs(x = "x", y="y")

P1 <- P0 + 
  scale_y_log10()
P2 <- P1 + 
  scale_x_log10() 
P3 <- P0 + scale_x_log10(breaks=c(1,2,4,8,16,32,64,128), limits=c(1,150))
P4 <- P0 + scale_x_log10(breaks=c(1, 3, 5, 10, 30, 50, 100, 500), limits=c(1,600))
P5 <- P0 + scale_x_log10(breaks=c(1, 3, 5, 10, 30, 50, 100, 300, 500), limits=c(1,600), labels = c(10, 20, 30, 40, 50, 60, 70, 80, 90))

save_graph(P0, "scales-linear.png")
save_graph(P1, "scales-semilog.png")
save_graph(P2, "scales-loglog.png")
# These will be edited to keep ust the x-axis
save_graph(P3, "scales-base2.png")
save_graph(P4, "scales-semidecade.png")
save_graph(P5, "scales-bogus.png")
  

P6 <- slice_plot(2 + 1.5*x ~ x, domain(x=c(0,5)), size=2) 
P7 <- P6 %>%
  gf_labs(y = "ln(output)", x = "input")
P8 <- P6 %>%
  gf_labs(y = "ln(output)", x = "ln(input)")
P9 <- slice_plot(10 - 2*x ~ x, domain(x=c(0,5)), size=2)  
P10 <- P9 %>%
  gf_labs(y = "ln(output)", x = "input")
P11 <- P9 %>%
  gf_labs(y = "ln(output)", x = "log(input)")

save_graph(P6, "line.png")
save_graph(P7, "exponential.png")
save_graph(P8, "power-law.png")
save_graph(P9, "line-neg.png")
save_graph(P10, "exponential-neg.png")
save_graph(P11, "power-law-neg.png")
```
