---
title: "Graphics for polynomial questions"
author: "Daniel Kaplan"
---

```{r include=FALSE}
library(mosaic)
library(mosaicCalc)
save_graph <- function(P, filename) {
  ggsave(filename, P, device="png", units="cm", width=10, scale=1, height=6, dpi="screen")
}
make_taylor_poly <- function(f, center=0) {
  a0 <- f(center)
  df <- D(f(x) ~ x)
  a1 <- df(center)
  ddf <- D(f(x) ~ x & x, .hstep=0.0001)
  a2 <- ddf(center)/2
  dddf <- D(ddf(x) ~ x, .hstep=0.001)
  a3 <- dddf(center)/6
  ddddf <- D(ddf(x) ~ x & x, .hstep=0.001)
  a4 <- ddddf(center)/24
  dddddf <- D(dddf(x) ~ x & x, .hstep=0.01)
  a5 <- dddddf(center)/120
  
  function(x, order=2) {
    a0*x^0 + (order>=1)*a1*(x-center) +
      (order>=2)*a2*(x-center)^2 +
      (order>=3)*a3*(x-center)^3 +
      (order>=4)*a4*(x-center)^4 +
      (order>=5)*a5*(x-center)^5
    
  }
}
```

```{r}
raw <- rfun(~ x, seed=273)
f <- makeFun(sin(x) * raw(x) ~ x)
slice_plot(f(x) ~ x, domain(x=-5:5)) %>%
  gf_refine(scale_x_continuous(breaks = -5:5)) %>%
save_graph("poly-01.png")
```


```{r}
raw <- rfun(~ x, seed=73)
f <- makeFun(cos(x/2) * raw(x) ~ x)
T <- make_taylor_poly(f, center=.6)
slice_plot(f(x) ~ x, domain(x=-5:5), npts=200) %>%
  gf_refine(scale_x_continuous(breaks = -5:5)) %>%
  slice_plot(T(x, 4) ~ x, color="magenta", domain(x=-1:2.5)) %>%
save_graph("poly-02.png")
T2 <- make_taylor_poly(f, center = -1)
slice_plot(f(x) ~ x, domain(x=-5:5), npts=200) %>%
  gf_refine(scale_x_continuous(breaks = -5:5)) %>%
  slice_plot(T2(x, 5) ~ x, color="magenta", domain(x=-3:1), size=2, alpha=0.5) %>%
slice_plot(T2(x, 3) ~ x, color="brown", domain(x=-3:0.5), size=2, alpha=0.5) %>%
  save_graph("poly-03.png")
```
